import type {
  Organization,
  CarbonEmission,
  EnergyUsage,
  WaterUsage,
  WasteData,
  ComplianceRecord,
  Report,
  Supplier,
  Team,
  AIInsight,
} from './db-models'

export const mockOrganization: Organization = {
  id: 'org-001',
  name: 'GreenTech Industries',
  industry: 'Technology',
  employees: 5000,
  headquarters: 'San Francisco, CA',
  sustainabilityGoals: [
    {
      id: 'goal-1',
      title: 'Carbon Neutral by 2030',
      target: 0,
      unit: 'kg CO2e',
      deadline: '2030-12-31',
      category: 'carbon',
      progress: 42,
      status: 'on-track',
    },
    {
      id: 'goal-2',
      title: '100% Renewable Energy',
      target: 100,
      unit: '%',
      deadline: '2028-12-31',
      category: 'energy',
      progress: 68,
      status: 'on-track',
    },
    {
      id: 'goal-3',
      title: 'Zero Waste to Landfill',
      target: 100,
      unit: '%',
      deadline: '2027-12-31',
      category: 'waste',
      progress: 55,
      status: 'at-risk',
    },
  ],
  createdAt: '2023-01-15',
  updatedAt: '2024-12-20',
}

export const mockCarbonEmissions: CarbonEmission[] = [
  {
    id: 'carbon-1',
    organizationId: 'org-001',
    source: 'energy',
    amount: 245000,
    date: '2024-12-20',
    facility: 'HQ Building',
    notes: 'Monthly coal usage',
    createdAt: '2024-12-20',
  },
  {
    id: 'carbon-2',
    organizationId: 'org-001',
    source: 'transportation',
    amount: 128000,
    date: '2024-12-20',
    facility: 'Fleet',
    notes: 'Vehicle emissions',
    createdAt: '2024-12-20',
  },
  {
    id: 'carbon-3',
    organizationId: 'org-001',
    source: 'supply-chain',
    amount: 892000,
    date: '2024-12-20',
    facility: 'Supply Chain',
    notes: 'Supplier emissions',
    createdAt: '2024-12-20',
  },
  {
    id: 'carbon-4',
    organizationId: 'org-001',
    source: 'waste',
    amount: 45000,
    date: '2024-12-20',
    facility: 'All Facilities',
    notes: 'Waste processing',
    createdAt: '2024-12-20',
  },
]

export const mockEnergyUsage: EnergyUsage[] = [
  {
    id: 'energy-1',
    organizationId: 'org-001',
    type: 'electricity',
    amount: 125000,
    cost: 18750,
    date: '2024-12-20',
    facility: 'HQ Building',
    createdAt: '2024-12-20',
  },
  {
    id: 'energy-2',
    organizationId: 'org-001',
    type: 'renewable',
    amount: 75000,
    cost: 7500,
    date: '2024-12-20',
    facility: 'Solar Array',
    createdAt: '2024-12-20',
  },
  {
    id: 'energy-3',
    organizationId: 'org-001',
    type: 'natural-gas',
    amount: 45000,
    cost: 4500,
    date: '2024-12-20',
    facility: 'HQ Building',
    createdAt: '2024-12-20',
  },
]

export const mockWaterUsage: WaterUsage[] = [
  {
    id: 'water-1',
    organizationId: 'org-001',
    source: 'municipal',
    amount: 250000,
    cost: 750,
    date: '2024-12-20',
    facility: 'HQ Building',
    createdAt: '2024-12-20',
  },
  {
    id: 'water-2',
    organizationId: 'org-001',
    source: 'recycled',
    amount: 150000,
    cost: 300,
    date: '2024-12-20',
    facility: 'Cooling System',
    createdAt: '2024-12-20',
  },
]

export const mockWaste: WasteData[] = [
  {
    id: 'waste-1',
    organizationId: 'org-001',
    type: 'general',
    amount: 1200,
    disposalMethod: 'Landfill',
    date: '2024-12-20',
    facility: 'HQ Building',
    createdAt: '2024-12-20',
  },
  {
    id: 'waste-2',
    organizationId: 'org-001',
    type: 'recycled',
    amount: 2800,
    disposalMethod: 'Recycling Center',
    date: '2024-12-20',
    facility: 'HQ Building',
    createdAt: '2024-12-20',
  },
  {
    id: 'waste-3',
    organizationId: 'org-001',
    type: 'organic',
    amount: 450,
    disposalMethod: 'Composting',
    date: '2024-12-20',
    facility: 'Cafeteria',
    createdAt: '2024-12-20',
  },
]

export const mockCompliance: ComplianceRecord[] = [
  {
    id: 'comp-1',
    organizationId: 'org-001',
    regulation: 'ISO 14001 Environmental Management',
    status: 'compliant',
    dueDate: '2025-06-30',
    lastAuditDate: '2024-03-15',
    notes: 'Annual certification audit passed',
    createdAt: '2024-03-15',
  },
  {
    id: 'comp-2',
    organizationId: 'org-001',
    regulation: 'Carbon Disclosure Project (CDP)',
    status: 'compliant',
    dueDate: '2025-02-28',
    lastAuditDate: '2024-09-20',
    notes: 'Submitted annual disclosure',
    createdAt: '2024-09-20',
  },
  {
    id: 'comp-3',
    organizationId: 'org-001',
    regulation: 'CSRD (Corporate Sustainability Reporting)',
    status: 'pending',
    dueDate: '2025-04-15',
    notes: 'Implementation in progress',
    createdAt: '2024-11-01',
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: 'supplier-1',
    organizationId: 'org-001',
    name: 'EcoPackaging Inc',
    category: 'Materials & Packaging',
    carbonFootprint: 2500,
    certifications: ['ISO 14001', 'B Corp'],
    riskScore: 15,
    lastAssessment: '2024-10-15',
    createdAt: '2024-01-10',
  },
  {
    id: 'supplier-2',
    organizationId: 'org-001',
    name: 'TechComponents Ltd',
    category: 'Electronics',
    carbonFootprint: 8900,
    certifications: ['ISO 14001'],
    riskScore: 42,
    lastAssessment: '2024-11-20',
    createdAt: '2024-02-15',
  },
  {
    id: 'supplier-3',
    organizationId: 'org-001',
    name: 'Global Logistics Co',
    category: 'Transportation',
    carbonFootprint: 15200,
    certifications: [],
    riskScore: 68,
    lastAssessment: '2024-09-10',
    createdAt: '2024-03-20',
  },
]

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    organizationId: 'org-001',
    name: 'Sustainability Champions',
    lead: 'Sarah Johnson',
    members: ['Sarah Johnson', 'Mike Chen', 'Emma Rodriguez', 'James Park'],
    responsibilities: ['Carbon tracking', 'Goal setting', 'Compliance reporting'],
    createdAt: '2023-06-01',
  },
  {
    id: 'team-2',
    organizationId: 'org-001',
    name: 'Energy Optimization',
    lead: 'David Kumar',
    members: ['David Kumar', 'Lisa Anderson', 'Robert Martinez'],
    responsibilities: ['Renewable energy', 'Efficiency improvements', 'Cost reduction'],
    createdAt: '2023-08-15',
  },
]

export const mockAIInsights: AIInsight[] = [
  {
    id: 'insight-1',
    organizationId: 'org-001',
    type: 'anomaly',
    title: 'Unusual Energy Spike Detected',
    description:
      'Your facility experienced a 35% increase in energy consumption yesterday compared to the weekly average.',
    impact: 'high',
    actionItems: [
      'Check HVAC system logs',
      'Review facility usage patterns',
      'Contact facilities team',
    ],
    generatedAt: '2024-12-20',
    resolved: false,
  },
  {
    id: 'insight-2',
    organizationId: 'org-001',
    type: 'recommendation',
    title: 'Switch to Renewable Energy Provider',
    description:
      'Based on your current consumption patterns and local market rates, switching to a renewable energy provider could save 40% on costs and reduce carbon footprint by 2000 tons annually.',
    impact: 'high',
    actionItems: ['Request quotes from 3 providers', 'Calculate ROI', 'Present to board'],
    generatedAt: '2024-12-19',
    resolved: false,
  },
  {
    id: 'insight-3',
    organizationId: 'org-001',
    type: 'forecast',
    title: 'Q1 2025 Energy Projection',
    description:
      'Current renewable capacity expansion should help you reach 75% renewable energy by Q1 2025, ahead of your target.',
    impact: 'medium',
    actionItems: ['Accelerate solar installation', 'Secure additional renewable contracts'],
    generatedAt: '2024-12-18',
    resolved: false,
  },
  {
    id: 'insight-4',
    organizationId: 'org-001',
    type: 'optimization',
    title: 'Water Usage Optimization Opportunity',
    description:
      'Upgrading to smart irrigation systems could reduce water consumption by 30% with a 2-year payback period.',
    impact: 'medium',
    actionItems: ['Get vendor quotes', 'Pilot program in one facility', 'Measure results'],
    generatedAt: '2024-12-17',
    resolved: true,
  },
]

export const mockReport: Report = {
  id: 'report-1',
  organizationId: 'org-001',
  type: 'quarterly',
  period: 'Q4 2024',
  generatedAt: '2024-12-20',
  data: {
    carbonEmissions: 1310000,
    energyUsage: 245000,
    waterUsage: 400000,
    wasteGenerated: 4450,
    keyInsights: [
      'Carbon emissions decreased by 8% compared to Q3',
      'Renewable energy adoption reached 68%',
      'Waste recycling rate improved to 63%',
      'Supply chain emissions remain the largest contributor',
    ],
    recommendations: [
      'Accelerate supplier sustainability programs',
      'Implement water recycling systems in all facilities',
      'Expand EV fleet to reduce transportation emissions',
      'Set stricter waste reduction targets',
    ],
  },
}
